name: ypb_photos
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: 1.0.2
  camera: 0.9.4+11
  get: 4.6.1
  hive: 2.0.5
  hive_flutter: 1.1.0
  image: 3.1.1
  loading_animations: 2.2.0
  path_provider: 2.0.9
  permission_handler: 8.3.0
  print_color: 3.0.5
  photo_view: 0.13.0
  sn_progress_dialog: 1.0.3
  velocity_x: 3.4.0

  flutter: 
    sdk: flutter

  
  
  


dev_dependencies: 
  flutter_lints: 1.0.0
  integration_test_tizen: 2.0.1
  lints: 1.0.1
  
  integration_test:
    sdk: flutter
  flutter_test: 
    sdk: flutter

get_cli: 
  sub_folder: false

flutter: 
  uses-material-design: true

